sonar.projectKey=biswajit-devsecops_gitops-school-management-system
sonar.organization=biswajit-devsecops
sonar.projectName=GitOps-School-Management-System
sonar.sources=.
# sonar.language=node
# sonar.nodejs.version=18
# sonar.sourceEncoding=UTF-8
# sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, **/test/**, **/__tests__/**, **/*.spec.js, **/*.test.js