services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://biswajit-manager123:bahubali3INOX@cluster0.68qohbt.mongodb.net/?appName=Cluster0
      PORT: 5000
      SECRET_KEY: biswajit1234
    networks:
      - mern

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - mern
  
networks:
  mern:
    driver: bridge