# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sms_frontend
---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-backend-deployment
  namespace: sms_frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sms-frontend
  template:
    metadata:
      labels:
        app: sms-frontend
    spec:
      containers:
      - name: sms-frontend
        image: biswajit134/sms_frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: sms-frontend-config
              key: REACT_APP_BASE_URL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"