# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sms-frontend
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-frontend
  namespace: sms-frontend
  labels:
    app: sms-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms-frontend
  template:
    metadata:
      labels:
        app: sms-frontend
    spec:
      containers:
      - name: sms-frontend
        image: biswajit134/sms_frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BASE_URL
          value: "http://sms-backend-service.sms-backend.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: sms-frontend-service
  namespace: sms-frontend
spec:
  selector:
    app: sms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---