
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: sms-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MONGO_URL

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: PORT

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: SECRET_KEY
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}