name:  build docker image and push to dockerhub
on:
    push:
        branches:
            - main
        paths-ignore:
            - "README.md"
            # - ".github/**"
            - "k8s_manifest/**"
            - "terraform/**"
            - "argocd/**"
            - "temp_sms_frontend_manifest/**"
            - "SS/**"

    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - run: echo "Checked out code successful"

        - name: Set up node js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        
        - name: build frontend
          run: |
            cd frontend
            npm install
            npm run build