name:  build docker image and push to dockerhub
on:
    push:
        branches:
            - main
        paths-ignore:
            - "README.md"
            - ".github/**"
            - "k8s_manifest/**"
            - "terraform/**"
            - "argocd/**"
            - "temp_sms_frontend_manifest/**"
            - "SS/**"
    workflow_dispatch:
        
        
jobs:
    compile:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - run: echo "Checked out code successful"


        - name: Set up node js
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Frontend Compilation (syntax check)
          run: |
            cd frontend
            find . -name "*.js" -exec node --check {} +

        - name: Backend Compilation (syntax check)
          run: |
            cd backend
            find . -name "*.js" -exec node --check {} +





    #     # sonarQube analysis
    # sonarqube:
    #   needs: compile
    #   runs-on: ubuntu-latest
    #   steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       # Disabling shallow clones is recommended for improving the relevancy of reporting
    #       fetch-depth: 0
    #   - name: SonarQube Scan
    #     uses: SonarSource/sonarcloud-github-action@master # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        
    #     with:
    #       args: >
    #         -Dsonar.projectKey=GitOps-School-Management-System


    #         -Dsonar.organization=biswajit134
     

    build:
        runs-on: ubuntu-latest
        needs: compile
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - run: echo "Checked out code successful"

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}


            - name: docker build images
              run: |
                docker build -t biswajit134/sms_frontend:latest ./frontend
                docker build -t biswajit134/sms_backend:latest ./backend
                echo "Docker images built successfully"
              
            - name: Push images to Docker Hub
              run: |
                docker push biswajit134/sms_frontend:latest
                docker push biswajit134/sms_backend:latest
                echo "Docker images pushed to Docker Hub successfully"
    

