name: Terraform Apply
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/TF_APPLY.yml'

  workflow_dispatch:

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:  
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: |
          pwd
          terraform init

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'  # Only run plan on push events, not on workflow_dispatch
        run: terraform plan -no-color
        continue-on-error: true  # Allow the workflow to continue even if the plan step fails
        

      - name: Terraform plan State
        if: steps.plan.outcome == 'failure'  # Only run this step if the plan step failed
        run: exit 1  # Exit with a non-zero code to indicate failure

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.plan.outcome == 'success'  # Only run apply on push events to main branch and if plan was successful
        run: terraform apply -auto-approve